#!/bin/sh
for i in verify asn1parse req dgst dh enc gendh errstr ca crl rsa x509 genrsa s_server s_client s_filter speed hashdir version pkcs7 crl2pkcs7 md2 md5 sha sha1 base64 des des3 idea rc4 rc2 des-ecb des-ede des-ede3 des-cbc des-ede-cbc des-ede3-cbc des-cfb des-ede-cfb des-ede3-cfb des-ofb des-ede-ofb des-ede3-ofb idea-cbc idea-ecb idea-cfb idea-ofb rc2-cbc rc2-ecb rc2-cfb rc2-ofb 
do
echo removing $i
/bin/rm -f $i
done
