/* mx/src/yd/ydcf.c */


/*
ORACLE, Copyright (c) 1982, 1983, 1986, 1990 ORACLE Corporation
ORACLE Utilities, Copyright (c) 1981, 1982, 1983, 1986, 1990, 1991 ORACLE Corp

Restricted Rights
This program is an unpublished work under the Copyright Act of the
United States and is subject to the terms and conditions stated in
your  license  agreement  with  ORACORP  including  retrictions on
use, duplication, and disclosure.

Certain uncopyrighted ideas and concepts are also contained herein.
These are trade secrets of ORACORP and cannot be  used  except  in
accordance with the written permission of ORACLE Corporation.
*/





#ifndef SYSI_ORACLE
#include <sysi.h>
#endif
#ifndef YS_ORACLE
#include <ys.h>
#endif
#ifndef YO_ORACLE
#include <yo.h>
#endif
#ifndef YSR_ORACLE
#include <ysr.h>
#endif
#ifndef YSL_ORACLE
#include <ysl.h>
#endif
#ifndef YSV_ORACLE
#include <ysv.h>
#endif
#ifndef YDYOIDL_ORACLE
#include <ydyoidl.h>
#endif
#ifndef YDIDL_ORACLE
#include <ydidl.h>
#endif
#ifndef YT_ORACLE
#include <yt.h>
#endif
#ifndef YDQ_ORACLE
#include <ydq.h>
#endif
#ifndef YDIM_ORACLE
#include <ydim.h>
#endif
#ifndef YSSTR_ORACLE
#include <ysstr.h>
#endif

#define ENTRY_POINT ydcfMain
#include <s0ysmain.c>



#define ydcfStr( s )	((s) ? s : (char*)"")
#define ydcfIdStr( id ) ((id) ? ysidToStr(id) : (char*)"")

#define YDCF_BATCHSIZE	((sb4)50)

#define YDCF_FAC	"YDUT"


static struct ysargmap ydcfmap[] =
{
  { 'a', "mnorbctl.unload-all=true", 0 },
  { 'i', "mnorbctl.load-from-file", 1 },
  { 'o', "mnorbctl.unload-to-file", 1 },
  { 0, (char *) 0, 0 }
};



STATICF void ydcfLoad( ydim_imr imr, char *file );
STATICF void ydcfUnload( ydim_imr imr, boolean all, char *file );

STATICF void ydcfField( char **s );
STATICF void ydcfStrField( char **s, char **dst );
STATICF void ydcfUB4( char **s, ub4 *dst );

STATICF char *ydcfGets( sysfp *fp, char *buf, size_t bufsiz );






boolean ydcfMain(dvoid *osdp, char *nm, sword argc, char **argv)
{
  boolean   ok;
  sword     sts;
  char      vbuf[80];
  ydim_imr  imr = (ydim_imr)0;
  boolean   all;
  char	    *infile;
  char	    *outfile;

  
  ysInit(osdp, nm);
  sts = ysArgParse(argc, argv, ydcfmap);
  if (sts == YSARG_VERSION)
    {
      yslError("Oracle Media Exchange ORB Daemon Load/Unload Utility");
      vbuf[0] = 0;
      yslError(ysVersion(vbuf, sizeof(vbuf)));
    }
  ok = (sts == YSARG_NORMAL);
  
  all = ysResGetBool("mnorbctl.unload-all");
  infile = (char*)ysResGetLast("mnorbctl.load-from-file");
  outfile = (char*)ysResGetLast("mnorbctl.unload-to-file");
    
  if( infile && outfile )
  {
    
    ysRecord(YS_PRODUCT, YDCF_FAC, (ub4)1520, YSLSEV_ERR, (char*)0, YSLNONE);
    ok = FALSE;
  }
  if( infile && all )
  {
    
    ysRecord(YS_PRODUCT, YDCF_FAC, (ub4)1521, YSLSEV_ERR, (char*)0, YSLNONE);
    ok = FALSE;
  }
  if (!ok)
    return(FALSE);
  
  yseTry
  {
    ytInit();
    yoInit();
    imr = (ydim_imr)yoBind(ydim_imr__id, (char*)0, (yoRefData*)0,(char*)0);
    if ( outfile )
      ydcfUnload( imr, all, outfile );
    else if( infile )
      ydcfLoad( imr, infile );
    yoRelease( (dvoid*)imr );
  };
  yseCatch( YS_EX_INTERRUPT )
  {
  }
  yseCatchAll
    yslPrint("%s caught exception %s, exiting\n",
	     ysProgName(), ysidToStr(yseExid));
  yseEnd;

  yseTry
  {
    yoTerm();
    ytTerm();
  }
  yseCatchAll
    yslError("%s caught exception %s while exiting\n", ysProgName(), yseExid );
  yseEnd;

  ysTerm(osdp);
    
  return TRUE;
}





STATICF void ydcfUnload( ydim_imr imr, boolean all, char *file )
{
  ydim_infoIterator  ii;
  ydim_infoList	    ilist;
  ydim_implInfo	    *info;
  ub4		    i, j;
  yoenv		    ev;
  sysfp		    *fp;
  CONST char	    *err; 

  yoEnvInit(&ev);

  if( !(fp = sysfpOpen( file, "w", SYSFPKIND_TEXT, &err ) ) )
  {
    
    ysRecord(YS_PRODUCT, YDCF_FAC, (ub4)1522, YSLSEV_ERR, (char*)0,
	     YSLSTR(file), YSLSTR("write"), YSLSTR(err), YSLEND );
    return;
  }

  DISCARD sysfpPrint(fp,
		     "# impl info config file machine generated by ydcf\n");
  ydim_imr_listImpl(imr, &ev, YDCF_BATCHSIZE, (char*)0, (char*)0, (char*)0,
		    &ilist, &ii );
  do
  {
    for( i = 0 ; i < ilist._length ; i++ )
    {
      info = &ilist._buffer[i];
      if( all || (info->pathName_ydim_implInfo &&
		  *info->pathName_ydim_implInfo ) )
      {
	DISCARD sysfpPrint(fp,  "%s|%s|%s|%s|%d|%d|%s|%d",
			   ysidToStr(info->intf_ydim_implInfo),
			   ydcfIdStr(info->impl_ydim_implInfo),
			   ydcfStr(info->host_ydim_implInfo),
			   ydcfStr(info->level_ydim_implInfo),
			   info->minInstances_ydim_implInfo,
			   info->maxInstances_ydim_implInfo,
			   ydcfStr(info->pathName_ydim_implInfo),
			   info->args_ydim_implInfo._length );
	for( j = 0 ; j < info->args_ydim_implInfo._length; j++ )
	  DISCARD sysfpPrint(fp, "|%s", info->args_ydim_implInfo._buffer[j] );
	DISCARD sysfpPrint(fp, "\n");
      }
    }

    ydim_infoList__free( &ilist, yoFree);

  } while(ii && ydim_infoIterator_next_n(ii, &ev, YDCF_BATCHSIZE, &ilist));

  if( ii )
    ydim_infoIterator_destroy( ii, &ev );

  sysfpClose( fp );
  yoEnvFree(&ev);
}



STATICF void ydcfLoad( ydim_imr imr, char *file )
{
  char buf[ 4096 ];
  char	*dup;
  ydim_implInfo  info;
  ub4	    j;
  char	    *s;
  ydim_info dimi;
  char	    **argv;
  yoenv	    ev;
  sysfp	    *fp;
  CONST char *err;

  yoEnvInit(&ev);

  if( !(fp = sysfpOpen( file, "r", SYSFPKIND_TEXT, &err ) ) )
  {
    
    ysRecord(YS_PRODUCT, YDCF_FAC, (ub4)1522, YSLSEV_ERR, (char*)0,
	     YSLSTR(file), YSLSTR("reading"), YSLSTR(err), YSLEND );
    return;
  }

  info.self_ydim_implInfo = (ydim_info)0;
  info.alist_ydim_implInfo._length = info.alist_ydim_implInfo._maximum = 0;
  info.alist_ydim_implInfo._buffer = (ydim_active*)0;
  info.args_ydim_implInfo._length = info.args_ydim_implInfo._maximum = 0;
  info.args_ydim_implInfo._buffer = (char**)0;

  while( ydcfGets( fp, buf, sizeof(buf) ) )
  {
    if( !buf[0] || buf[0] == '#' )
      continue;
    dup = ysStrDupWaf( buf, (ysmaf)0 );
    s = buf;
    ydcfStrField( &s, &info.intf_ydim_implInfo );
    ydcfStrField( &s, &info.impl_ydim_implInfo );
    ydcfStrField( &s, &info.host_ydim_implInfo );
    ydcfStrField( &s, &info.level_ydim_implInfo );
    ydcfUB4( &s, &info.minInstances_ydim_implInfo );
    ydcfUB4( &s, &info.maxInstances_ydim_implInfo );
    ydcfStrField( &s, &info.pathName_ydim_implInfo );
    ydcfUB4( &s, &info.args_ydim_implInfo._length );
    if( info.args_ydim_implInfo._length )
    {
      argv = (char **)ysmGlbAlloc( sizeof(char**), "args");
      info.args_ydim_implInfo._buffer = argv;
      for( j = 0 ; j < info.args_ydim_implInfo._length; j++ )
	ydcfStrField( &s, &info.args_ydim_implInfo._buffer[j] );
    }
    info.args_ydim_implInfo._maximum = info.args_ydim_implInfo._length;

    ydim_imr_addInfoGlobal( imr, &ev, &info, &dimi );
    ydim_implInfo__free( &info, ysmFGlbFree );
    ysmFGlbFree( (dvoid*)dup );
  }
  sysfpClose( fp );
  yoEnvFree(&ev);
}

STATICF void ydcfField( char **s )
{
  char *q = *s;
  boolean quoted;

  for( quoted = FALSE; *q && !quoted && *q != '|' ; q++)
    if( quoted )
      quoted = FALSE;
    else
      quoted = *q == '~';

  
  if( *q == '|' )
    *q++ = 0;

  *s = q;
}

STATICF void ydcfStrField( char **s, char **dst )
{
  char *q = *s;
  ydcfField( s );
  *dst = *q ? ysStrDupWaf( q, (ysmaf)0 ) : (char*)0;
}

STATICF void ydcfUB4( char **s, ub4 *dst )
{
  char *q = *s;
  ydcfField( s );
  *dst = (ub4)atol( q );
}


STATICF char *ydcfGets( sysfp *fp, char *buf, size_t bufsiz )
{
  sword ch;
  size_t i;

  
  bufsiz--;
  for( i = 0 ; i < bufsiz && !sysfpGetc( fp, &ch ) && ch != '\n' ; )
    buf[i++] = (char)ch;
  buf[i] = 0;
  return( i ? buf : (char*)0 );
}


