; generated by Norcroft RISC OS ARM C vsn 5.06 (Acorn Computers Ltd) [Feb 21 1995]

        AREA |C$$code|, CODE, READONLY
|x$codeseg|

        IMPORT  __rt_stkovf_split_small
        IMPORT  bn_expand2
        EXPORT  BN_lshift1
BN_lshift1
        MOV      ip,sp
        STMDB    sp!,{a1,a2,v1-v6,fp,ip,lr,pc}
        SUB      fp,ip,#4
        CMP      sp,sl
        BLLT     __rt_stkovf_split_small
        MOV      v1,a1
        MOV      v2,a2
        SUB      sp,sp,#4
        TEQ      v1,v2
        BEQ      |L00008c.J5.BN_lshift1|
        LDR      a1,[v2,#&c]
        STR      a1,[v1,#&c]
        MOV      a2,#&20
        LDR      a1,[v2,#4]
        ADDS     a2,a2,a1,LSL #5
        BPL      |L000044.J11.BN_lshift1|
        ADD      a2,a2,#&1f
|L000044.J11.BN_lshift1|
        MOV      a2,a2,ASR #5
        LDR      a1,[v1,#8]
        CMP      a2,a1
        BGT      |L00005c.J10.BN_lshift1|
        MOV      a1,v1
        B        |L000070.J9.BN_lshift1|
|L00005c.J10.BN_lshift1|
        MOV      a1,#&20
        LDR      a2,[v2,#4]
        ADD      a2,a1,a2,LSL #5
        MOV      a1,v1
        BL       bn_expand2
|L000070.J9.BN_lshift1|
        TEQ      a1,#0
        BNE      |L000080.J8.BN_lshift1|
        MOV      a1,#0
        LDMDB    fp,{v1-v6,fp,sp,pc}^
|L000080.J8.BN_lshift1|
        LDR      a1,[v2,#4]
        STR      a1,[v1,#4]
        B        |L0000dc.J16.BN_lshift1|
|L00008c.J5.BN_lshift1|
        MOV      a2,#&20
        LDR      a1,[v2,#4]
        ADDS     a1,a2,a1,LSL #5
        BPL      |L0000a0.J21.BN_lshift1|
        ADD      a1,a1,#&1f
|L0000a0.J21.BN_lshift1|
        MOV      a1,a1,ASR #5
        LDR      a2,[v1,#8]
        CMP      a1,a2
        BGT      |L0000b8.J20.BN_lshift1|
        MOV      a1,v1
        B        |L0000cc.J19.BN_lshift1|
|L0000b8.J20.BN_lshift1|
        MOV      a1,#&20
        LDR      a2,[v2,#4]
        ADD      a2,a1,a2,LSL #5
        MOV      a1,v1
        BL       bn_expand2
|L0000cc.J19.BN_lshift1|
        TEQ      a1,#0
        BNE      |L0000dc.J16.BN_lshift1|
        MOV      a1,#0
        LDMDB    fp,{v1-v6,fp,sp,pc}^
|L0000dc.J16.BN_lshift1|
        LDR      v6,[v2,#0]
        LDR      v5,[v1,#0]
        MOV      v3,#0
        MOV      a1,#0
        STR      a1,[sp,#0]
|L0000f0.J27.BN_lshift1|
        LDR      a2,[sp,#0]
        LDR      a1,[v2,#4]
        CMP      a2,a1
        BLT      |L000114.J26.BN_lshift1|
        B        |L00013c.J29.BN_lshift1|
|L000104.J28.BN_lshift1|
        LDR      a1,[sp,#0]
        ADD      a1,a1,#1
        STR      a1,[sp,#0]
        B        |L0000f0.J27.BN_lshift1|
|L000114.J26.BN_lshift1|
        LDR      v4,[v6],#4
        ORR      a2,v3,v4,LSL #1
        STR      a2,[v5],#4
        TST      v4,#&80000000
        BEQ      |L000130.J33.BN_lshift1|
        MOV      a1,#1
        B        |L000134.J32.BN_lshift1|
|L000130.J33.BN_lshift1|
        MOV      a1,#0
|L000134.J32.BN_lshift1|
        MOV      v3,a1
        B        |L000104.J28.BN_lshift1|
|L00013c.J29.BN_lshift1|
        TEQ      v3,#0
        BEQ      |L000158.J36.BN_lshift1|
        MOV      a1,#1
        STR      a1,[v5,#0]
        LDR      a1,[v1,#4]
        ADD      a1,a1,#1
        STR      a1,[v1,#4]
|L000158.J36.BN_lshift1|
        MOV      a1,#1
        LDMDB    fp,{v1-v6,fp,sp,pc}^
        ADD      sp,sp,#4
        LDMDB    fp,{v1-v6,fp,sp,pc}^

        IMPORT  BN_set_word
        EXPORT  BN_rshift1
BN_rshift1
        MOV      ip,sp
        STMDB    sp!,{a1,a2,v1-v6,fp,ip,lr,pc}
        SUB      fp,ip,#4
        CMP      sp,sl
        BLLT     __rt_stkovf_split_small
        MOV      v1,a1
        MOV      v2,a2
        SUB      sp,sp,#4
        LDR      a1,[v2,#4]
        CMP      a1,#1
        BGT      |L0001b8.J5.BN_rshift1|
        LDR      a1,[v2,#0]
        LDR      a1,[a1,#0]
        TEQ      a1,#0
        BNE      |L0001b8.J5.BN_rshift1|
        MOV      a1,v1
        MOV      a2,#0
        BL       BN_set_word
        MOV      a1,#1
        LDMDB    fp,{v1-v6,fp,sp,pc}^
|L0001b8.J5.BN_rshift1|
        TEQ      v2,v1
        BEQ      |L000218.J10.BN_rshift1|
        LDR      a1,[v2,#4]
        MOVS     a2,a1,LSL #5
        BPL      |L0001d0.J16.BN_rshift1|
        ADD      a2,a2,#&1f
|L0001d0.J16.BN_rshift1|
        MOV      a2,a2,ASR #5
        LDR      a1,[v1,#8]
        CMP      a2,a1
        BGT      |L0001e8.J15.BN_rshift1|
        MOV      a1,v1
        B        |L0001f8.J14.BN_rshift1|
|L0001e8.J15.BN_rshift1|
        LDR      a1,[v2,#4]
        MOV      a2,a1,LSL #5
        MOV      a1,v1
        BL       bn_expand2
|L0001f8.J14.BN_rshift1|
        TEQ      a1,#0
        BNE      |L000208.J13.BN_rshift1|
        MOV      a1,#0
        LDMDB    fp,{v1-v6,fp,sp,pc}^
|L000208.J13.BN_rshift1|
        LDR      a1,[v2,#4]
        STR      a1,[v1,#4]
        LDR      a1,[v2,#&c]
        STR      a1,[v1,#&c]
|L000218.J10.BN_rshift1|
        LDR      v6,[v2,#0]
        LDR      a1,[v1,#0]
        STR      a1,[sp,#0]
        MOV      v4,#0
        LDR      a1,[v2,#4]
        SUB      v3,a1,#1
|L000230.J22.BN_rshift1|
        CMP      v3,#0
        BGE      |L000244.J21.BN_rshift1|
        B        |L000270.J24.BN_rshift1|
|L00023c.J23.BN_rshift1|
        SUB      v3,v3,#1
        B        |L000230.J22.BN_rshift1|
|L000244.J21.BN_rshift1|
        LDR      v5,[v6,v3,LSL #2]
        ORR      a1,v4,v5,LSR #1
        LDR      a2,[sp,#0]
        STR      a1,[a2,v3,LSL #2]
        TST      v5,#1
        BEQ      |L000264.J28.BN_rshift1|
        MOV      a1,#&80000000
        B        |L000268.J27.BN_rshift1|
|L000264.J28.BN_rshift1|
        MOV      a1,#0
|L000268.J27.BN_rshift1|
        MOV      v4,a1
        B        |L00023c.J23.BN_rshift1|
|L000270.J24.BN_rshift1|
        LDMIA    v1,{a1,a3}
        ADD      a1,a1,a3,LSL #2
        SUB      a2,a1,#4
|L00027c.J33.BN_rshift1|
        LDR      a1,[v1,#4]
        CMP      a1,#0
        BGT      |L00029c.J32.BN_rshift1|
        B        |L0002b0.J35.BN_rshift1|
|L00028c.J34.BN_rshift1|
        LDR      a1,[v1,#4]
        SUB      a1,a1,#1
        STR      a1,[v1,#4]
        B        |L00027c.J33.BN_rshift1|
|L00029c.J32.BN_rshift1|
        LDR      a3,[a2],#-4
        TEQ      a3,#0
        BEQ      |L0002ac.J37.BN_rshift1|
        B        |L0002b0.J35.BN_rshift1|
|L0002ac.J37.BN_rshift1|
        B        |L00028c.J34.BN_rshift1|
|L0002b0.J35.BN_rshift1|
        MOV      a1,#1
        LDMDB    fp,{v1-v6,fp,sp,pc}^
        ADD      sp,sp,#4
        LDMDB    fp,{v1-v6,fp,sp,pc}^

        IMPORT  _fprintf
        IMPORT  fflush
        IMPORT  memset
        EXPORT  BN_lshift
BN_lshift
        MOV      ip,sp
        STMDB    sp!,{a1-a3,v1-v6,fp,ip,lr,pc}
        SUB      fp,ip,#4
        CMP      sp,sl
        BLLT     __rt_stkovf_split_small
        MOV      v1,a1
        MOV      v2,a2
        MOV      v3,a3
        SUB      sp,sp,#&10
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        ADD      a2,pc,#L00032c-.-8
        BL       _fprintf
        LDR      a1,[v2,#&c]
        STR      a1,[v1,#&c]
        LDR      a1,[v2,#4]
        ADDS     a2,v3,a1,LSL #5
        BPL      |L000310.J8.BN_lshift|
        ADD      a2,a2,#&1f
|L000310.J8.BN_lshift|
        MOV      a2,a2,ASR #5
        LDR      a1,[v1,#8]
        CMP      a2,a1
        BGT      |L000334.J7.BN_lshift|
        MOV      a1,v1
        B        |L000344.J6.BN_lshift|
L000328
        IMPORT  __iob
        DCD     __iob+&50
L00032c
        DCB     &62,&6e,&6c,&73
        DCB     &3a,&31,&0a,&00
|L000334.J7.BN_lshift|
        LDR      a1,[v2,#4]
        ADD      a2,v3,a1,LSL #5
        MOV      a1,v1
        BL       bn_expand2
|L000344.J6.BN_lshift|
        TEQ      a1,#0
        BNE      |L000354.J5.BN_lshift|
        MOV      a1,#0
        LDMDB    fp,{v1-v6,fp,sp,pc}^
|L000354.J5.BN_lshift|
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        ADD      a2,pc,#L000414-.-8
        BL       _fprintf
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        BL       fflush
        MOV      a4,v2
        STMDB    sp!,{a4}
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        MOV      a4,v3
        MOV      a3,v1
        ADD      a2,pc,#L00041c-.-8
        BL       _fprintf
        ADD      sp,sp,#4
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        BL       fflush
        MOV      a4,v3
        LDR      a3,[v2,#4]
        STMDB    sp!,{a3,a4}
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        LDR      a4,[v1,#0]
        MOV      a3,v1
        ADD      a2,pc,#L00042c-.-8
        BL       _fprintf
        ADD      sp,sp,#8
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        BL       fflush
        MOVS     a1,v3
        BPL      |L0003f8.J12.BN_lshift|
        ADD      a1,a1,#&1f
|L0003f8.J12.BN_lshift|
        MOV      v6,a1,ASR #5
        MOVS     a1,v3
        BPL      |L00044c.J14.BN_lshift|
        RSB      a1,a1,#0
        AND      a1,a1,#&1f
        RSB      a1,a1,#0
        B        |L000450.J15.BN_lshift|
L000414
        DCB     &62,&6e,&6c,&73
        DCB     &3a,&32,&0a,&00
L00041c
        DCB     &72,&3d,&25,&70
        DCB     &20,&6e,&3d,&25
        DCB     &64,&20,&61,&3d
        DCB     &25,&70,&0a,&00
L00042c
        DCB     &72,&3d,&25,&70
        DCB     &20,&72,&2d,&3e
        DCB     &64,&3d,&25,&70
        DCB     &20,&61,&2d,&3e
        DCB     &74,&6f,&70,&3d
        DCB     &25,&64,&20,&6e
        DCB     &3d,&25,&64,&0a
        DCB     &00,&00,&00,&00
|L00044c.J14.BN_lshift|
        AND      a1,a1,#&1f
|L000450.J15.BN_lshift|
        STR      a1,[sp,#&c]
        LDR      a2,[sp,#&c]
        RSB      a1,a2,#&20
        STR      a1,[sp,#8]
        LDR      a1,[v2,#0]
        STR      a1,[sp,#4]
        LDR      v5,[v1,#0]
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        MOV      a3,v5
        ADD      a2,pc,#L0004e8-.-8
        BL       _fprintf
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        BL       fflush
        MOV      a2,#0
        LDR      a1,[v2,#4]
        ADD      a1,a1,v6
        STR      a2,[v5,a1,LSL #2]
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        ADD      a2,pc,#L0004f0-.-8
        BL       _fprintf
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        BL       fflush
        LDR      a1,[sp,#&c]
        TEQ      a1,#0
        BNE      |L000518.J17.BN_lshift|
        LDR      a1,[v2,#4]
        SUB      v4,a1,#1
|L0004dc.J20.BN_lshift|
        CMP      v4,#0
        BGE      |L000500.J19.BN_lshift|
        B        |L000514.J22.BN_lshift|
L0004e8
        DCB     &74,&3d,&25,&70
        DCB     &0a,&00,&00,&00
L0004f0
        DCB     &62,&6e,&6c,&73
        DCB     &3a,&33,&0a,&00
|L0004f8.J21.BN_lshift|
        SUB      v4,v4,#1
        B        |L0004dc.J20.BN_lshift|
|L000500.J19.BN_lshift|
        LDR      a1,[sp,#4]
        LDR      a1,[a1,v4,LSL #2]
        ADD      a2,v6,v4
        STR      a1,[v5,a2,LSL #2]
        B        |L0004f8.J21.BN_lshift|
|L000514.J22.BN_lshift|
        B        |L00057c.J24.BN_lshift|
|L000518.J17.BN_lshift|
        LDR      a1,[v2,#4]
        SUB      v4,a1,#1
|L000520.J26.BN_lshift|
        CMP      v4,#0
        BGE      |L000534.J25.BN_lshift|
        B        |L00057c.J24.BN_lshift|
|L00052c.J27.BN_lshift|
        SUB      v4,v4,#1
        B        |L000520.J26.BN_lshift|
|L000534.J25.BN_lshift|
        LDR      a1,[sp,#4]
        LDR      a1,[a1,v4,LSL #2]
        STR      a1,[sp,#0]
        ADD      a1,v6,v4
        ADD      a1,v5,a1,LSL #2
        LDR      a1,[a1,#4]
        LDR      a2,[sp,#8]
        LDR      a3,[sp,#0]
        ORR      a1,a1,a3,LSR a2
        ADD      a2,v6,v4
        ADD      a2,v5,a2,LSL #2
        STR      a1,[a2,#4]
        LDR      a1,[sp,#&c]
        LDR      a2,[sp,#0]
        MOV      a2,a2,LSL a1
        ADD      a1,v6,v4
        STR      a2,[v5,a1,LSL #2]
        B        |L00052c.J27.BN_lshift|
|L00057c.J24.BN_lshift|
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        ADD      a2,pc,#L000628-.-8
        BL       _fprintf
        MOV      a4,v2
        MOV      a3,v1
        MOV      a2,#4
        STMDB    sp!,{a2-a4}
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        MOV      a4,v6
        MOV      a3,v5
        ADD      a2,pc,#L000630-.-8
        BL       _fprintf
        ADD      sp,sp,#&c
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        BL       fflush
        MOV      a3,v6,LSL #2
        MOV      a1,v5
        MOV      a2,#0
        BL       memset
        LDR      a1,[v2,#4]
        ADD      a1,a1,v6
        ADD      a1,a1,#1
        STR      a1,[v1,#4]
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        ADD      a2,pc,#L000658-.-8
        BL       _fprintf
        SUB      sp,sp,#4
        LDMIA    v1,{a1,a2}
        ADD      a1,a1,a2,LSL #2
        SUB      a1,a1,#4
        STR      a1,[sp,#0]
|L000618.J34.BN_lshift|
        LDR      a1,[v1,#4]
        CMP      a1,#0
        BGT      |L000670.J33.BN_lshift|
        B        |L00068c.J36.BN_lshift|
L000628
        DCB     &62,&6e,&6c,&73
        DCB     &3a,&34,&0a,&00
L000630
        DCB     &74,&3d,&25,&70
        DCB     &20,&6e,&77,&3d
        DCB     &25,&64,&20,&73
        DCB     &69,&7a,&65,&6f
        DCB     &66,&28,&74,&5b
        DCB     &30,&5d,&29,&3d
        DCB     &25,&64,&20,&72
        DCB     &3d,&25,&70,&20
        DCB     &61,&3d,&25,&70
        DCB     &0a,&00,&00,&00
L000658
        DCB     &62,&6e,&6c,&73
        DCB     &3a,&35,&0a,&00
|L000660.J35.BN_lshift|
        LDR      a1,[v1,#4]
        SUB      a1,a1,#1
        STR      a1,[v1,#4]
        B        |L000618.J34.BN_lshift|
|L000670.J33.BN_lshift|
        LDR      a1,[sp,#0]
        LDR      a2,[a1],#-4
        TEQ      a2,#0
        STR      a1,[sp,#0]
        BEQ      |L000688.J38.BN_lshift|
        B        |L00068c.J36.BN_lshift|
|L000688.J38.BN_lshift|
        B        |L000660.J35.BN_lshift|
|L00068c.J36.BN_lshift|
        ADD      sp,sp,#4
        LDR      a1,[pc, #L000328-.-8]
        LDR      ip,[sl,#-0]
        ADD      a1,ip,a1
        ADD      a2,pc,#L0006ac-.-8
        BL       _fprintf
        MOV      a1,#1
        LDMDB    fp,{v1-v6,fp,sp,pc}^
L0006ac
        DCB     &62,&6e,&6c,&73
        DCB     &3a,&36,&0a,&00
        ADD      sp,sp,#&10
        LDMDB    fp,{v1-v6,fp,sp,pc}^

        EXPORT  BN_rshift
BN_rshift
        MOV      ip,sp
        STMDB    sp!,{a1-a3,v1-v6,fp,ip,lr,pc}
        SUB      fp,ip,#4
        CMP      sp,sl
        BLLT     __rt_stkovf_split_small
        MOV      v1,a1
        MOV      v2,a2
        SUB      sp,sp,#&10
        LDR      a1,[v2,#&c]
        STR      a1,[v1,#&c]
        LDR      a1,[fp,#-&28]
        CMP      a1,#0
        BGE      |L0006f4.J5.BN_rshift|
        ADD      a1,a1,#&1f
|L0006f4.J5.BN_rshift|
        MOV      v5,a1,ASR #5
        LDR      a1,[fp,#-&28]
        CMP      a1,#0
        BGE      |L000714.J7.BN_rshift|
        RSB      a1,a1,#0
        AND      a1,a1,#&1f
        RSB      a1,a1,#0
        B        |L000718.J8.BN_rshift|
|L000714.J7.BN_rshift|
        AND      a1,a1,#&1f
|L000718.J8.BN_rshift|
        STR      a1,[sp,#4]
        LDR      a2,[sp,#4]
        RSB      a1,a2,#&20
        STR      a1,[sp,#8]
        LDR      a1,[v2,#4]
        CMP      v5,a1
        BLE      |L000748.J10.BN_rshift|
        MOV      a1,v1
        MOV      a2,#0
        BL       BN_set_word
        MOV      a1,#1
        LDMDB    fp,{v1-v6,fp,sp,pc}^
|L000748.J10.BN_rshift|
        LDR      a1,[v2,#4]
        SUB      a1,a1,v5
        MOV      a2,#&20
        ADDS     a1,a2,a1,LSL #5
        BPL      |L000760.J17.BN_rshift|
        ADD      a1,a1,#&1f
|L000760.J17.BN_rshift|
        MOV      a1,a1,ASR #5
        LDR      a2,[v1,#8]
        CMP      a1,a2
        BGT      |L000778.J16.BN_rshift|
        MOV      a1,v1
        B        |L000790.J15.BN_rshift|
|L000778.J16.BN_rshift|
        LDR      a1,[v2,#4]
        SUB      a2,a1,v5
        MOV      a1,#&20
        ADD      a2,a1,a2,LSL #5
        MOV      a1,v1
        BL       bn_expand2
|L000790.J15.BN_rshift|
        TEQ      a1,#0
        BNE      |L0007a0.J14.BN_rshift|
        MOV      a1,#0
        LDMDB    fp,{v1-v6,fp,sp,pc}^
|L0007a0.J14.BN_rshift|
        LDR      a1,[v2,#0]
        ADD      v6,a1,v5,LSL #2
        LDR      v3,[v1,#0]
        LDR      a1,[v2,#4]
        SUB      a1,a1,v5
        STR      a1,[sp,#&c]
        LDR      a1,[sp,#&c]
        STR      a1,[v1,#4]
        LDR      a1,[sp,#4]
        TEQ      a1,#0
        BNE      |L0007f8.J21.BN_rshift|
        LDR      a1,[sp,#&c]
        ADD      v4,a1,#1
|L0007d4.J25.BN_rshift|
        CMP      v4,#0
        BGT      |L0007e8.J24.BN_rshift|
        B        |L0007f4.J27.BN_rshift|
|L0007e0.J26.BN_rshift|
        SUB      v4,v4,#1
        B        |L0007d4.J25.BN_rshift|
|L0007e8.J24.BN_rshift|
        LDR      a2,[v6],#4
        STR      a2,[v3],#4
        B        |L0007e0.J26.BN_rshift|
|L0007f4.J27.BN_rshift|
        B        |L000850.J30.BN_rshift|
|L0007f8.J21.BN_rshift|
        LDR      a2,[v6],#4
        STR      a2,[sp,#0]
        MOV      v4,#0
|L000804.J33.BN_rshift|
        LDR      a1,[sp,#&c]
        CMP      v4,a1
        BLT      |L00081c.J32.BN_rshift|
        B        |L000850.J30.BN_rshift|
|L000814.J34.BN_rshift|
        ADD      v4,v4,#1
        B        |L000804.J33.BN_rshift|
|L00081c.J32.BN_rshift|
        LDR      a1,[sp,#4]
        LDR      a2,[sp,#0]
        MOV      a1,a2,LSR a1
        STR      a1,[v3,#0]
        LDR      a1,[v6],#4
        STR      a1,[sp,#0]
        LDR      a1,[sp,#8]
        LDR      a2,[sp,#0]
        MOV      a2,a2,LSL a1
        LDR      a1,[v3,#0]
        ORR      a1,a2,a1
        STR      a1,[v3],#4
        B        |L000814.J34.BN_rshift|
|L000850.J30.BN_rshift|
        MOV      a1,#0
        STR      a1,[v3,#0]
        LDR      a1,[v1,#4]
        LDR      a3,[v1,#0]
        ADD      a1,a3,a1,LSL #2
        SUB      a2,a1,#4
|L000868.J42.BN_rshift|
        LDR      a1,[v1,#4]
        CMP      a1,#0
        BGT      |L000888.J41.BN_rshift|
        B        |L00089c.J44.BN_rshift|
|L000878.J43.BN_rshift|
        LDR      a1,[v1,#4]
        SUB      a1,a1,#1
        STR      a1,[v1,#4]
        B        |L000868.J42.BN_rshift|
|L000888.J41.BN_rshift|
        LDR      a3,[a2],#-4
        TEQ      a3,#0
        BEQ      |L000898.J46.BN_rshift|
        B        |L00089c.J44.BN_rshift|
|L000898.J46.BN_rshift|
        B        |L000878.J43.BN_rshift|
|L00089c.J44.BN_rshift|
        MOV      a1,#1
        LDMDB    fp,{v1-v6,fp,sp,pc}^
        ADD      sp,sp,#&10
        LDMDB    fp,{v1-v6,fp,sp,pc}^

        AREA |C$$data|,DATA

|x$dataseg|

        END
