.TH MNNIO_INTRO 4 "31 August 1994"
.SH NAME
mnnio_intro - introduction to Media Net network interfaces
.SH DESCRIPTION
.LP
This section describes network interfaces available with Media Net.
Media Net provides for a variety of network data links through an
abstraction called a network interface object.  mnnio(4) describes
the construction of a network interface object.  This page describes
how existing NIO objects are defined and used.
.LP
Some objects are addressable by means of an address that is specific
to the type of data link.  These addresses, called physical addresses,
are grouped into address families.  Most Media Net programs and utilities
which accept physical address specifications from the command line or the
environment expect the physical address to be in the following form:
.LP
.RS
<address-family>:<family-specific-address>
.RE
.LP
where <address-family> is an identifier up to four characters long that
identifies the family, and <family-specific-address> is a string understood
by the network interface objects for that family.
.SH LIST OF SUPPORTED NETWORK INTERFACES
.nf
.ta +10n; +20n; +10n
Name	Appears on Page	Description
UDP	mnnio_udp(4)	UDP/IP interface object
IPC	mnnio_ipc(4)	nCube IPC interface object
.SH SEE ALSO
mnnio(4), mnars(8).
