.TH mnnPullBuf 4 "31 August 1994"
.SH NAME
mnnPullBuf, mnnTestBuf - pull a buffer to send
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnnio.h>
.LP
sb4 mnnPullBuf(mnnio *nio, mnnpa *pa, ub1 *buf, size_t len);
.LP
sb4 mnnTestBuf(mnnio *nio);
.SH DESCRIPTION
nio is a network interface object that is capable of sending (i.e.
MNNFLG_SEND is set), but has no defined send() routine.
.LP
mnnPullBuf() gets the next buffer to be sent and writes it into the
space pointed to by buf.  len is the maximum size of the buffer.  If
the packet to be sent is larger than the buffer, it will be fragmented
to fit inside the buffer.  If it cannot be fragmented, it will be
dropped.
.LP
mnnTestBuf() returns the number of bytes contains in the packet to
be sent.  This value will never be larger than pktmax.
.SH USAGE
mnnPullBuf() is used by NIOs that want to control the rate at which data
is sent through them.  Rather than Media Net calling a send routine to send
data, it simply queues it up internally, and allows the NIO to pull packets
from Media Net at its own rate.
.SH RETURN VALUES
These routines return the number of bytes in the next packet on success;
otherwise, they may return one of the following errors:
.TP 20
MNERR_WOULDBLOCK
No packets are pending.
.TP 20
MNERR_TRUNCATE
mnnPullBuf() was called with a buffer that was too small and the packet
could not be fragmented.
.SH SEE ALSO
mnnPushBuf(4), mnnTrace(4), mnnio(4).
