.TH mnnPushBuf 4 "31 August 1994"
.SH NAME
mnnPushBuf - push a buffer that was received
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnnio.h>
.LP
void mnnPushBuf(mnnio *nio, mnnpa *pa, ub1 *buf, size_t len);
.SH DESCRIPTION
nio is a network interface object that is capable of receiving (i.e.
MNNFLG_RECV is set), but has no defined recv() routine.
.LP
mnnPushBuf() takes the data in the buffer pointed to by buf and copies
up to len bytes into a Media Net buffer.  pa should be the physical address
where this packet arrived from (if meaningful).
.SH USAGE
mnnPushBuf() is used by NIOs that cannot be allowed to block or need
to filter packets being pushed into Media Net.  Usually, these NIOs
work by having O/S interrupts generated when data arrives, and then,
within the interrupt handler, calling mnnPushBuf() with the arriving
data.
.LP
mnnPushBuf() may be called during an O/S interrupt.
.SH SEE ALSO
mnnPullBuf(4), mnnTrace(4), mnnio(4).
