.TH mnnSubnet 4 "31 August 1994"
.SH NAME
mnnSubnet - get the Media Net address for the NIO
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnnio.h>
.LP
void mnnSubnet(mnnio *nio, mna *subnet);
.SH DESCRIPTION
mnnSubnet() gets the Media Net address assigned to the NIO and writes
it to subnet.
.SH SEE ALSO
mna(3), mnnio(4).
