.TH mnnTrace 4 "31 August 1994"
.SH NAME
mnnTrace - trace Media Net packets
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnnio.h>
.LP
void mnnTrace(const char *pfx, ub1 *buf, size_t len);
.SH DESCRIPTION
mnnTrace() is used for debugging purposes to trace packets passing
into and out of Media Net.  buf and len describe a raw buffer that
was either just passed to the NIO for sending or just received by
an NIO.  mnnTrace() causes a one-line description of the packet
to be logged.
.SH SEE ALSO
mnInit(3), mnnio(4).
