.TH mnnTeardown 4 "7 September 1994"
.SH NAME
mnnTeardown - teardown a network interface object
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnnio.h>
.LP
void mnnTeardown(mnnio *nio);
.SH DESCRIPTION
nio is a network interface object actively being used by Media Net.  Usually,
it is one which is capable of receiving (MNNFLG_RECV) or is at the head end
of a circuit-based NIO (MNNFLG_SEND | MNNFLG_CIRC).
.LP
mnnTeardown() will release the address previously assigned to the network
interface object (if any) and request a new address to be assigned (if
appropriate).  It will also discard any inbound or outbound packets
pending on the network interface object.  Subsequent packets arriving
at the node destined for the old address will result in DESTINATION
NOT REACHABLE control messages being returned to the sender.
.SH SEE ALSO
mna(3), mnInit(3), mnnio(4).
