
/*************************************************************************
*
* ibrowerr.h        !!!! DO NOT EDIT THIS FILE !!!!
*
* ICA Browser error codes
*
* NOTE: generated from: \nt\private\citrix\ibrowser\ibrowerr.mc
*
*
* copyright notice: Copyright 1995-1997, Citrix Systems Inc.
*
* Author:  Brad Pedersen 11/2/95
*
*************************************************************************/



//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: BR_ERROR_SUCCESS
//
// MessageText:
//
//  No error.
//
#define BR_ERROR_SUCCESS                 0L

//
// MessageId: BR_ERROR_INVALID_HEADER
//
// MessageText:
//
//  Invalid ICA Browser command header received.
//
#define BR_ERROR_INVALID_HEADER          1L

//
// MessageId: BR_ERROR_INVALID_COMMAND
//
// MessageText:
//
//  Invalid ICA Browser command received.
//
#define BR_ERROR_INVALID_COMMAND         2L

//
// MessageId: BR_ERROR_INVALID_PARAMETER
//
// MessageText:
//
//  ICA Browser command contains an invalid parameter.
//
#define BR_ERROR_INVALID_PARAMETER       3L

//
// MessageId: BR_ERROR_NOT_ENOUGH_MEMORY
//
// MessageText:
//
//  Not enough memory.
//
#define BR_ERROR_NOT_ENOUGH_MEMORY       4L

//
// MessageId: BR_ERROR_IO_ERROR
//
// MessageText:
//
//  I/O Error.
//
#define BR_ERROR_IO_ERROR                5L

//
// MessageId: BR_ERROR_READ_TIMEOUT
//
// MessageText:
//
//  Read Timeout.
//
#define BR_ERROR_READ_TIMEOUT            6L

//
// MessageId: BR_ERROR_PING_BYTECOUNT
//
// MessageText:
//
//  Invalid byte count received on ping.
//
#define BR_ERROR_PING_BYTECOUNT          7L

//
// MessageId: BR_ERROR_PING_ADDRESS
//
// MessageText:
//
//  Invalid address received on ping.
//
#define BR_ERROR_PING_ADDRESS            8L

//
// MessageId: BR_ERROR_PING_DATA
//
// MessageText:
//
//  Invalid data received on ping.
//
#define BR_ERROR_PING_DATA               9L

//
// MessageId: BR_ERROR_THREAD_CREATE
//
// MessageText:
//
//  Error creating ICA Browser thread.
//
#define BR_ERROR_THREAD_CREATE           10L

//
// MessageId: BR_ERROR_TIMER_CREATE
//
// MessageText:
//
//  Error creating ICA Browser timer.
//
#define BR_ERROR_TIMER_CREATE            11L

//
// MessageId: BR_ERROR_WINSOCK_STARTUP
//
// MessageText:
//
//  Error initializing winsock for ICA Browser.
//
#define BR_ERROR_WINSOCK_STARTUP         12L

//
// MessageId: BR_ERROR_DATABASE_ADD
//
// MessageText:
//
//  Error adding data to ICA Browser database.
//
#define BR_ERROR_DATABASE_ADD            13L

//
// MessageId: BR_ERROR_DATABASE_LOCATE
//
// MessageText:
//
//  Unable to locate name in ICA Browser database.
//
#define BR_ERROR_DATABASE_LOCATE         14L

//
// MessageId: BR_ERROR_INVALID_REPLY
//
// MessageText:
//
//  Invalid ICA Browser command received on request.
//
#define BR_ERROR_INVALID_REPLY           16L

//
// MessageId: BR_ERROR_INVALID_SEQUENCE
//
// MessageText:
//
//  Invalid ICA Browser command sequence received.
//
#define BR_ERROR_INVALID_SEQUENCE        17L

//
// MessageId: BR_ERROR_APPLICATION_LOCATE
//
// MessageText:
//
//  Unable to locate application name in ICA Browser database.
//
#define BR_ERROR_APPLICATION_LOCATE      18L

//
// MessageId: BR_ERROR_NO_MASTER
//
// MessageText:
//
//  Unable to locate master ICA Browser for specified transport.
//
#define BR_ERROR_NO_MASTER               19L

//
// MessageId: BR_ERROR_REGISTRY
//
// MessageText:
//
//  Error accessing ICA Browser registry data.
//
#define BR_ERROR_REGISTRY                20L

//
// MessageId: BR_ERROR_LOG_OPEN
//
// MessageText:
//
//  Error opening ICA Browser log file.
//
#define BR_ERROR_LOG_OPEN                21L

//
// MessageId: BR_ERROR_IPX_NOT_AVAILABLE
//
// MessageText:
//
//  IPX protocol is not available.
//
#define BR_ERROR_IPX_NOT_AVAILABLE       22L

//
// MessageId: BR_ERROR_TCP_NOT_AVAILABLE
//
// MessageText:
//
//  TCP/IP protocol is not available.
//
#define BR_ERROR_TCP_NOT_AVAILABLE       23L

//
// MessageId: BR_ERROR_NETBIOS_NOT_AVAILABLE
//
// MessageText:
//
//  NETBIOS protocol is not available.
//
#define BR_ERROR_NETBIOS_NOT_AVAILABLE   24L

//
// MessageId: BR_ERROR_NO_LOAD_BALANCE_LICENSE
//
// MessageText:
//
//  Server does not have a load balance license.
//
#define BR_ERROR_NO_LOAD_BALANCE_LICENSE 25L

//
// MessageId: BR_ERROR_WRONG_OS_VERSION
//
// MessageText:
//
//  OS version does not match expected version.
//
#define BR_ERROR_WRONG_OS_VERSION        26L

//
// MessageId: BR_ERROR_NO_OS_VERSION
//
// MessageText:
//
//  Could not validate OS version.
//
#define BR_ERROR_NO_OS_VERSION           27L

//
// MessageId: MSG_BROWSER_STARTED
//
// MessageText:
//
//  The ICA Browser service was started.
//
#define MSG_BROWSER_STARTED              1000L

//
// MessageId: MSG_BROWSER_THREAD_EXITED
//
// MessageText:
//
//  ICA Browser thread exited due to an error. See previous event for more details.
//
#define MSG_BROWSER_THREAD_EXITED        1001L

//
// MessageId: MSG_NO_IPX_BROWSER
//
// MessageText:
//
//  IPX ICA Browser failed to initialize.  See previous event for more details.
//
#define MSG_NO_IPX_BROWSER               1002L

//
// MessageId: MSG_NO_TCP_BROWSER
//
// MessageText:
//
//  TCP/IP ICA Browser failed to initialize.  See previous event for more details.
//
#define MSG_NO_TCP_BROWSER               1003L

//
// MessageId: MSG_NO_NETBIOS_BROWSER
//
// MessageText:
//
//  NETBIOS ICA Browser failed to initialize.  See previous event for more details.
//
#define MSG_NO_NETBIOS_BROWSER           1004L

//
// MessageId: MSG_BROWSER_MASTER_DOWNLEVEL
//
// MessageText:
//
//  The master ICA Browser is not the latest version.  It may be incompatible.
//
#define MSG_BROWSER_MASTER_DOWNLEVEL     1005L

