/* -*-c-*- */

#define FILETYPE_DIRECTORY	0x1000

#define FILETYPE_TEXT		0xfff
#define FILETYPE_DATA		0xffd
#define FILETYPE_SPRITE		0xff9
#define FILETYPE_TIFF		0xff0
#define FILETYPE_UNIXEX		0xFE6
#define FILETYPE_DOS		0xfe4
#define FILETYPE_HTML		0xfaf
#define FILETYPE_JPEG		0xc85
#define FILETYPE_GOPHER		0xb62
#define FILETYPE_XBM		0xb61
#define FILETYPE_PNG		0xb60
#define FILETYPE_URL		0xb28
#define FILETYPE_URI		0xf91
#define FILETYPE_DRAWFILE	0xAFF
#define FILETYPE_GIF		0x695
#define FILETYPE_XPM		0x301
