/* profile.c - Runtime support for count profiling in Fresco
 */

#include <stdio.h>
#include "profile.h"

/* Global data in autogenerated profdat.c */


extern void profile_init(void)
{
}


extern void profile_report(FILE *fp)
{
#if PROFILE
    int x;

    fprintf(fp, "\nFRESCO PROFILE COUNT STATISTICS\n===============================\n\n");
    
    for (x = 0; x < PROF_NUM_32BIT; x++)
    {
	fprintf(fp, "%-40s: %d\n",
		prof_global[x].name,
		prof_global[x].count);
    }

    fprintf(fp, "\n");

    for (x = 0; x < PROF_NUM_64BIT; x++)
    {
	/* Assumes long long int is 64 - not with Norcroft! */
	fprintf(fp, "%-40s: %Ld\n", 
		prof_global64[x].name, 
		prof_global64[x].count);
    }

    fprintf(fp, "\n");

    fprintf(fp, "%-40s: %g\n", "Heap calls per HTML input byte",
	    ( prof_global[PROF_MALLOC].count +
	      prof_global[PROF_CALLOC].count +
	      prof_global[PROF_REALLOC].count +
	      prof_global[PROF_FREE].count ) / (double)prof_global[PROF_HTML_BYTES].count
	    );

    fprintf(fp, "\n");
#endif
}



/* eof */


