// Copyright (c) 1995 by Oracle Corporation.  All Rights Reserved.
//
// yostd.idl - Oracle Standard Definitions for CORBA IDL

// These are definitions Oracle types for those that are used to them.
// The CORBA IDL has strict definitions for the meanings of the integer
// scalar types (unlike C) that makes this mapping consistent and meaningful
// on all platforms.

#ifndef YOSTD_ORACLE
#define YOSTD_ORACLE

#define ub1 octet
#define ub2 unsigned short
#define sb2 short
#define ub4 unsigned long
#define sb4 long
#define sb8 long long

// The following are some definitions for some types that we have defined
// in header files and would like the IDL writer to have access to.
#define ysid string

interface yoevt;

module yostd
{
  typedef sequence <string> stringList;
  typedef sequence <Object> objList;
  typedef sequence <octet> octetSeq;
};

#endif YOSTD_ORACLE

