/* mx/src/inc/yrdesc.idl */


/*
ORACLE, Copyright (c) 1982, 1983, 1986, 1990 ORACLE Corporation
ORACLE Utilities, Copyright (c) 1981, 1982, 1983, 1986, 1990, 1991 ORACLE Corp

Restricted Rights
This program is an unpublished work under the Copyright Act of the
United States and is subject to the terms and conditions stated in
your  license  agreement  with  ORACORP  including  retrictions on
use, duplication, and disclosure.

Certain uncopyrighted ideas and concepts are also contained herein.
These are trade secrets of ORACORP and cannot be  used  except  in
accordance with the written permission of ORACLE Corporation.
*/


#ifndef YRDESC_IDL_ORACLE
#define YRDESC_IDL_ORACLE

#ifndef YOSTD_ORACLE
#include "yostd.idl"
#endif

#ifndef YRTYPES_IDL_ORACLE
#include "yrtypes.idl"
#endif

interface yrType;



struct yrBriefDesc      {
  string name;            yrid id;                yrid defined_in;        yrvers version;
};



struct yrStructMbr
{
  string name;
  TypeCode type;          yrType type_def;
};
typedef sequence <yrStructMbr> yrStructMbrSeq;



struct yrStructDesc
{
  yrBriefDesc brief;
  TypeCode type;
  yrStructMbrSeq mbrs;
};



typedef yrStructDesc yrExceptDesc;
typedef sequence <yrExceptDesc> yrExceptDescSeq;



struct yrUnionMbr
{
  string name;
  any label;
  TypeCode type;
  yrType type_def;
};
typedef sequence <yrUnionMbr> yrUnionMbrSeq;



struct yrUnionDesc
{
  yrBriefDesc brief;
  TypeCode type;
  yrType disctype;
  yrUnionMbrSeq arms;
};



struct yrConstDesc
{
  yrBriefDesc brief;
  TypeCode type;
  any value;
};



struct yrParmDesc
{
  string name;
  TypeCode type;
  yrType type_def;
  yomode mode;
};
typedef sequence <yrParmDesc> yrParmDescSeq;



struct yrAttrDesc
{
  yrBriefDesc brief;
  TypeCode type;
  yrAttrMode mode;
};
typedef sequence <yrAttrDesc> yrAttrDescSeq;



struct yrOpDesc
{
  yrBriefDesc brief;
  TypeCode result;
  yrOpMode mode;
  yrParmDescSeq parameters;
  yrExceptDescSeq exceptions;
};
typedef sequence <yrOpDesc> yrOpDescSeq;



struct yrIntfDesc
{
  yrBriefDesc brief;
  yrOpDescSeq operations;
  yrAttrDescSeq attributes;
  yridSeq base_interfaces;
  TypeCode type;
};



struct yrStringDesc
{
  ub4 bound;
  TypeCode type;
};



struct yrArrayDesc
{
  ub4 length;
  yrType element_type;
  TypeCode type;
};



struct yrSeqDesc
{
  ub4 bound;
  yrType element_type;
  TypeCode type;
};



struct yrAliasDesc
{
  yrType base_type;
  TypeCode type;
};



typedef sequence <yrConstDesc> yrEnumMbrDescSeq;
struct yrEnumDesc
{
  yrBriefDesc brief;
  TypeCode type;
  yrEnumMbrDescSeq mbrs;
};



struct yrPrimDesc
{
  yrpk kind;
  TypeCode type;
};



union yrDesc switch (yrdk)
{
  case yrdkAttribute:
    yrAttrDesc attval;
  case yrdkConstant:
    yrConstDesc cval;
  case yrdkStruct:
    yrStructDesc sval;
  case yrdkException:
    yrExceptDesc exval;
  case yrdkInterface:
    yrIntfDesc intfval;
  case yrdkOperation:
    yrOpDesc opval;
  case yrdkAlias:
    yrAliasDesc aval;
  case yrdkUnion:
    yrUnionDesc uval;
  case yrdkEnum:
    yrEnumDesc eval;
  case yrdkPrimitive:
    yrPrimDesc pval;
  case yrdkString:
    yrStringDesc strval;
  case yrdkSequence:
    yrSeqDesc seqval;
  case yrdkArray:
    yrArrayDesc arrval;
  case yrdkModule:
    yrBriefDesc brief;
  default:
    ub4 dummy;
};
typedef sequence <yrDesc> yrDescSeq;

#endif 
