#!/bin/sh
FROM=${FRESCO}/http
FROM1=${FRESCO}
TO=..
cp -p $FROM/certs.c $TO/c/certs
cp -p $FROM/csfs.c $TO/c/csfs
cp -p $FROM/csfs.h $TO/h/csfs
cp -p $FROM/http.c $TO/c/http
cp -p $FROM/http.h $TO/h/http
cp -p $FROM/mimemap.c $TO/c/mimemap
cp -p $FROM/mimemap.h $TO/h/mimemap
cp -p $FROM/module.c $TO/c/module
cp -p $FROM/notlayer.h $TO/h/notlayer
cp -p $FROM/predirect.c $TO/c/predirect
#
cp -p $FROM/httppub.h $TO/h/httppub
cp -p $FROM/pads.h $TO/h/pads
#
cp -p $FROM1/commonsrc/status.h $TO/h/status
#
cp -p $FROM1/layers/riscos/files.c $TO/c/files
cp -p $FROM1/layers/files.h $TO/h/files
cp -p $FROM1/layers/riscos/file.c $TO/c/file
cp -p $FROM1/layers/file.h $TO/h/file
#cp -p $FROM1/layers/riscos/layers.c $TO/c/layers
#cp -p $FROM1/layers/layers.h $TO/h/layers
cp -p $FROM1/layers/platforms.h $TO/h/platforms
#
cp -p $FROM1/libs/riscos_lib/types.h $TO/h/types
#
echo got files from Master source tree
