.TH MNORBCTL 8 "5 October 1995" "Oracle Media Net"
.SH NAME
mnorbctl - Oracle Media Net ORB Configuration Utility
.SH SYNOPSIS
.nf
mnorbctl [ -a] [-i infile ][-o outfile] 
.SH DESCRIPTION
mnorbctl loads and unloads spawning information from the implementation
repository in mnorbsrv(8) ORB daemons.  The format of the information is
described in mnorbctl(5).
.SH OPTIONS
.TP
-i infile
Load data from the specified file into the orb daemons.
.TP
-o
Unload implementation entries from the orb daemon to the specified file.
By default, only include those that have spawning information.
.TP
-a
In conjunction with -o, unload all entries, even those with no spawning 
data.
.SH ENVIRONMENT
.TP
OMN_ADDR
The physical address of the address server to use.
.SH SEE ALSO
mnorbsrv(8), mnorbls(1), mnorbctl(5)




