.TH MNORBSRV 8 "17 June 1996" "Oracle Media Net"
.SH NAME
mnorbsrv - Oracle Media Net Object Request Broker (ORB) Daemon
.SH SYNOPSIS
.nf
mnorbsrv [ -x ] 
.SH DESCRIPTION
mnorbsrv provides the implementation repository, request forwarding, and
process spawning operations in an OMN ORB.  There must be at least one
running in each OMN address space.  For load balancing purposes, more
than one mnorbsrv may be run, on the same or different hosts.  If there is
no mnorbsrv on a host, it can't have any processes dynamically started by
the mnorbsrv.

The mnorbsrv provides the following interfaces, defined in ydidl.idl:
.TP
\fBydrt\fP
Request Router.  Requests are not routed using an object interface,
but controls for the router and statistics are available through ydrt.
.TP
\fBydim\fP
The implementation repository.  Used to catalog active, inactive, and potentially active implementations.
.TP
\fBydmt\fP
Metrics used by the router.  These are updated with
measured values by the mnorbmet(8).
.TP
\fBydsp\fP
Process spawner
.TP
\fBydch\fP 
Object clearinghouse, for persistant stateful objects (currently
non-functional).
.SH OPTIONS
.TP
-x
Turn on route tracing.
.SH ENVIRONMENT
.TP
OMN_ADDR
The physical address of the address server to use.
.SH SEE ALSO
mnorbls(1), mnprocstat(1), mnorbctl(8), mnorbmet(8)
