.TH MNC 1 "25 October 1994"
.SH NAME
mnc - Media Net IDL Compiler
.SH SYNOPSIS
.nf
mnc [ -E ] [ -I path ] [ -D name[=value] ] [ -V ] [ -o outputfile ]
	sourcefile
.SH OVERALL OPTIONS
.TP
-E
Run the pre-processor only.  The pre-processed output is sent to the
standard output, or to a file named with the -o option.
.TP
-V
Print version number.
.SH PRE-PROCESSOR OPTIONS
The pre-processor recognizes all ANSI C pre-processor directives
and operators.  All directives are passed through to the header
file that is produced (if any).  Included files are processed
but not emitted.  Included files are searched for in the following
manner:  When the "filename" notation is used, first the directory
in which the current file is located is searched.  Then, the list
of directories created with the -I option is searched.  Finally,
a list of standard directories defined during installation is
searched.
.LP
Definitions which appear in included files
are processed, but nothing is emitted for these definitions.
During pre-processing, the following identifiers (in addition
to those required by the ANSI C standard) are defined:
.TP 10
#define MNIDL(arg)  arg
.TP
-I path
Append the path to the list of directories to search for #include
files with relative filenames.  The space separating the option
from the path argument is optional.
.TP
-D name[=value]
Define the macro name with the value value or the string "1" if
no value is given.  The space separating the option from the
name is optional.
