.TH MNLN 1 "13 December 1994"
.SH NAME
mnln - create a symbolic link
.SH SYNOPSIS
.nf
mnln [ -g physical-address ] path-name alias-name
.SH DESCRIPTION
mnln creates a symbolic link in the Media Net name server.  path-name
is the name that is to be used as the value of the alias-name.
alias-name is the name of the symbolic link itself.
.LP
Generally, the path-name is an absolute name that identifies another
entry in the namespace.  The named entry need not exist at the time
of the creation of the symbolic link.  The alias-name may or may not
be a relative name.  The full path of the alias name must be unique
within the name space.
.LP
.RS
.nf
example% setenv OMN_CWD /user1
example% mnln /server server
example% mnls
Name                Address              Program ID
user1/server                             -> /server              
(1 entry)
.fi
.RE
.LP
Symbolic links may be redefined with different values at any time.
Symbolic links may be removed with mnrm(1).
.SH ENVIRONMENT
.TP
OMN_ADDR
The physical address of the address server to use.
.TP
OMN_CWD
The current working directory within which to resolve names.
.SH SEE ALSO
mnrm(1), mznm(8).
