.TH MNLS 1 "13 December 1994"
.SH NAME
mnls - list the contents of a Media Net namespace
.SH SYNOPSIS
.nf
mnls [ -v ] [ -g physical-address ] [ -i physical-address ]
.SH DESCRIPTION
mnls queries the Media Net name server for all entries in the namespace.
Entries are one of three types: program entries, named ports, and symbolic
links.  For each program entry, mnls prints the name, address, and program
ID.  For each named port, mnls prints the name and address; the text "(named
port)" will appear in place of the program ID.  For each symbolic link,
mnls prints the name of the symbolic link and the value to which it is
aliased in place of the program ID.  This value is denoted by the symbol
"->" appearing before the alias value.
.SH OPTIONS
.TP
-v
Print the version used.
.TP
-g physical-address
Specify the physical address to use to reach the address server.  If
not specified, the value in the environment variable OMN_ADDR is used.
.TP
-i physical-address
Same as -g except that corresponding NIO will be opened in an interrupt-based
mode if possible.
.SH ENVIRONMENT
.TP
OMN_ADDR
The physical address of the address server to use.
.SH SEE ALSO
mznm(8).
