.TH MNORBLS 1 "8 March 1996" "Oracle Media Net"
.SH NAME
mnorbls - Oracle Media Net ORB Implementation Listing Program
.SH SYNOPSIS
.nf
mnorbls [ -as ]
.SH DESCRIPTION
mnorbls queries the implementation repository in a mnorbsrv(8) and displays
information about the known implementations.
.LP
The basic output shows fields for the interface, the implementation, the
host, and the number of active entries.  Spawnable interfaces always have
at least one active entry.
.LP
The -a output adds lines containing the string form of the runtime object
address, and an indication whether the implementation is suspended.
.LP
The -s output adds lines showing the path, arguments, minInstances and
maxInstances.
.SH OPTIONS
.TP
-a
Also show details about active implementations.
.TP
-s
Also show spawning information.
.SH ENVIRONMENT
.TP
OMN_ADDR
The physical address of the address server to use.
.SH SEE ALSO
mnorbsrv(8), mnorbctl(8)
