.TH MNPROCSTAT 1 "8 March 1996 1995" "Oracle Media Net"
.SH NAME
mnprocstat - Oracle Media Net ORB Process Listing Program
.SH SYNOPSIS
.nf
mnprocstat
.SH DESCRIPTION
mnprocstat queries the spawner in a mnorbsrv(8) and displays
information about the known processes.  Processes become known either
when they are spawned by the ydsp, or when an implementation in the
process becomes active.
.LP
The output shows fields for the host, the pid, process affinity, the
process name, whether the process is known to be spawned or is an
orphan, and the state known to the spawner.  The possible states are
.TP
start_ok
if the process is running.
.TP
start_fail
if the process was spawned but failed during the spawn operation.
.TP
exit_ok
if the process was spawned and exited with sucessful status.
.TP
exit_bad
if the process was spawned and exited with bad status.
.TP
exit_unknown
if the process was not spawned by the reporting yd and has exited.
.SH ENVIRONMENT
.TP
OMN_ADDR
The physical address of the address server to use.
.SH SEE ALSO
mnorbsrv(8), mnorbctl(8)
