.TH MNRID 1 "7 September 1994"
.SH NAME
mnrid - generate an RPC identifier
.SH SYNOPSIS
.nf
mnrid [ -c ] symbol
.SH DESCRIPTION
mnrid generates unique RPC program and component identifier for use with
RPC servers.  It produces declarations for a program identifier and
component identifier for names derived from symbol.  The declarations
are printed to the standard output.
.SH OPTIONS
.TP
-c
Generate the declarations to conform to Oracle coding standards.
.SH USAGE
mnrid is used to generate unique program identifiers.  It also generates
a single component identifier.  Obviously, one or the other of these may
be used independently.  The version number for the identifier is always
generated as version 1.0.  These version numbers may be changed manually
for subsequent versions of the same program.
.SH SEE ALSO
mnrCreateServer(3), mnrpc_intro(3).
