.TH MNRM 1 "13 December 1994"
.SH NAME
mnrm - remove a symbolic link
.SH SYNOPSIS
.nf
mnrm [ -g physical-address ] path-name
.SH DESCRIPTION
mnrm removes the given name from the Media Net namespace.  If the name
is relative, it is resolved relative to the current working directory.
.SH WARNINGS
Care should be taken when using this operation.  Removing the true
registered name of a server makes the server unreachable, and there
is no way to reinstate the server name without restarting the server
itself.
.SH SEE ALSO
mnln(1), mznm(8).
