.TH YDLS 8 "5 October 1995"
.SH NAME
ydls - Media Exchange Implementation Listing Program
.SH SYNOPSIS
.nf
ydls [ -as ]
.SH DESCRIPTION
ydls queries the implementation repository in a yd(8) and displays
information about the known implementations.
.LP
The basic output shows fields for the interface, the implementation, the
host, and the number of active entries.  Spawnable interfaces always have
at least one active entry.
.LP
The -a output adds lines containing the string form of each active
implementaton.
.LP
The -s output adds lines showing the path, arguments, minInstances and
maxInstances.
.SH OPTIONS
.TP
-a
Also show details about active implementations.
.TP
-s
Also show spawning information.
.SH ENVIRONMENT
.TP
OMN_ADDR
The physical address of the address server to use.
.SH SEE ALSO
yd(8), ydcf(8)





