# Makefile for Font Manager
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 25-May-94  AMcC         Created.
#

COMPONENT = FontManager
TARGET    = Fonts
HEADER1   = Font

include StdTools
include AAsmModule

# Dynamic dependencies:
