dnl Process this file with autoconf to produce a configure script.

dnl Any filename in your sources directory will do here.
AC_INIT([DebugLib/DebugLib.h.in])

dnl Standard initial settings to automatically detect package name and version
dnl and set up automake.
AC_CONFIG_AUX_DIR(config)
AC_CANONICAL_BUILD
AC_CANONICAL_HOST
AC_CANONICAL_TARGET
PACE_INIT_VERSIONNUM
AM_INIT_AUTOMAKE($pace_versionnum_packagename, $pace_versionnum_packagevers)
AM_CONFIG_HEADER(config.h)

dnl Checks for programs.
AC_PROG_CC
AC_ISC_POSIX

dnl Checks for libraries.

dnl I am a library - so I need libtool
AC_PROG_LIBTOOL
AC_SUBST(LIBTOOL_DEPS)

dnl Checks for header files.
AC_HEADER_STDC
AC_CHECK_HEADERS(errno.h limits.h locale.h string.h stdbool.h time.h)

dnl Now check for anything outside your component
dnl from the standard include directories.
AC_CHECK_HEADERS(sys/types.h sys/errno.h syslog.h sys/syslog.h)
AC_CHECK_HEADERS(sys/socket.h netinet/in.h arpa/inet.h)
AC_CHECK_HEADERS(powertv.h pk.h)

dnl These headers are required for the public DebugLib/DebugLib.h header file
PACE_CONDITIONAL_HEADER(stdarg_h,stdarg.h)
PACE_CONDITIONAL_HEADER(stddef_h,stddef.h)
PACE_CONDITIONAL_HEADER(stdbool_h,stdbool.h)

dnl Checks for typedefs, structures, and compiler characteristics.
AC_C_CONST
AC_TYPE_SIZE_T
AC_HEADER_TIME

dnl Check whether the compiler can be asked to flag suspect parameters to
dnl varargs functions like printf (see m4 macros in config directory)
PACE_CC_VARARGS_PRAGMAS

dnl Pull in the build options from the config directory
PACE_DEBUGLIB_BUILD_OPTIONS

ACX_PTHREAD

dnl Checks for library functions.
AC_PROG_GCC_TRADITIONAL

dnl Substitute the build directories in the makefiles.
PACE_PROJECT_DIRS

dnl Ensure that the config.sub etc. files are found during "make dist"
AC_SUBST(ac_aux_dir)
AC_SUBST(LIBOBJS)

dnl Add any further output files to this list
AC_CONFIG_FILES([
  DebugLib/DebugLib.h Makefile config/Makefile DebugLib/Makefile src/Makefile
  ])

dnl Generate the output files
AC_OUTPUT
