#!/usr/bin/perl
#
# create.pl - called from the list of email addresses generated by accounts.pl,
#             displays a blank form for the new account.
#

print "Content-type: text/html\r\n\r\n";
use strict;

# global variables
#
my ($query)   = $ENV{'QUERY_STRING'};
my ($header_html) = "Create_H";

my (@usernames, @passwords, @addresses, @flags, @localpophostnames, @localsmtphostnames);
my ($global_pop_hostname, $global_smtp_hostname);
my ($edithosts);

my ($public_path, $accounts_file);


# main
#

if (get_public_path())
{
  $accounts_file = $public_path."/NCMail/Users";

  output_header_html($header_html);
  read_accounts_file($accounts_file);
  output_buttons();
  output_main_html();
}


# read the accounts file
#
sub read_accounts_file
{
  my ($file) = @_;
  my ($line, $record_number, @fields, $temp, $i);

  if (!open(FILE,$file))
  {
      print("Error opening $file : $!\n");
      return;
  }

  @usernames = ("");
  @passwords = ("");
  @addresses = ("");
  @flags = ("");
  @localpophostnames = ("");
  @localsmtphostnames = ("");
  $record_number = 0;
  $edithosts = 0;

  # **** Start the hidden form which passes the information to the javascript functions
  print "<FORM NAME=records>";
  print "<INPUT TYPE=HIDDEN NAME=hidden_path VALUE=".$public_path.">";

  # **** Search through the users file for the records
  while ($line = <FILE>)
  {
    @fields = split(/ /,$line);

    if ($fields[0] eq "POP3hostname")
    {
      $global_pop_hostname = substr($fields[1], 0, length($fields[1]) - 1);
    }

    if ($fields[0] eq "SMTPhostname")
    {
      $global_smtp_hostname = substr($fields[1], 0, length($fields[1]) - 1);
    }

    if ($fields[0] eq "EditHosts")
    {
      $edithosts = substr($fields[1], 0, length($fields[1]) - 1);

      print "<INPUT TYPE=HIDDEN NAME=hidden_edithosts VALUE=".$edithosts.">";
    }

    if ($fields[0] eq "pop3username")
    {
      $usernames[$record_number] = substr($fields[1], 0, length($fields[1]) - 1);

      print "<INPUT TYPE=HIDDEN NAME=hidden_username".$record_number." VALUE=".$usernames[$record_number].">";
    }

    if ($fields[0] eq "pop3password")
    {
      $passwords[$record_number] = substr($fields[1], 0, length($fields[1]) - 1);
    }

    if ($fields[0] eq "emailaddress")
    {
      ($addresses[$record_number],$temp) = split("@", substr($fields[1], 0, length($fields[1]) - 1));

      print "<INPUT TYPE=HIDDEN NAME=hidden_address".$record_number." VALUE=".$addresses[$record_number].">";
    }

    if ($fields[0] eq "flags")
    {
      $flags[$record_number] = substr($fields[1], 0, length($fields[1]) - 1);

      # increment the record_number when the flags are found as it is the last part of each account record
      $record_number += 1;

    }
  }

  print "<INPUT TYPE=HIDDEN NAME=hidden_number_of_records VALUE=".$record_number.">";
  print "</FORM>\n\n";

  close (FILE);

  # Check that the fields are all filled, even if just the default settings
  for ($i = 0; $i < $record_number; $i++)
  {
    if ($localpophostnames[$i] eq "" or $localpophostnames[$i] eq "-") { $localpophostnames[$i] = $global_pop_hostname; }
    if ($localsmtphostnames[$i] eq "" or $localsmtphostnames[$i] eq "-") { $localsmtphostnames[$i] = $global_smtp_hostname; }
  }
}

# output_header_html
#
sub output_header_html
{
  my ($file) = @_;
  my ($line);

  # **** Output the header of the page, with the buttons
  if (!open(FILE,$file))
  {
      print("Error opening $file : $!\n");
      return;
  }

  # **** read the file in
  while ($line = <FILE>)
  {
      print("$line");
  }

  close (FILE);
}


# output_main_html
#
sub output_main_html
{
  # **** Output the start of the table
  print "<BR><BR>\n<CENTER>\n\n";
  print "<TABLE BORDER=0 WIDTH=100%>\n";

  if (!$edithosts)
  {
    print "<TR>\n";
    print "  <TD ALIGN=RIGHT WIDTH=160 HEIGHT=22><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>êêcreate_popserverëë</TD><TD WIDTH=5></TD><TD COLSPAN=2><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë COLOR='#888888'>".$global_pop_hostname."</TD>\n";
    print "</TR>\n";

    print "<TR>\n";
    print "  <TD ALIGN=RIGHT WIDTH=160 HEIGHT=22><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>êêcreate_smtpserverëë</TD><TD WIDTH=5></TD><TD COLSPAN=2><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë COLOR='#888888'>".$global_smtp_hostname."</TD>\n";
    print "</TR>\n";

    # Set the form fields for the pop and smtp as hidden values
    print "<INPUT TYPE=HIDDEN NAME=\"pophostname\" VALUE=\"".$global_pop_hostname."\">\n";
    print "<INPUT TYPE=HIDDEN NAME=\"smtphostname\" VALUE=\"".$global_smtp_hostname."\">\n";

    print "<TR><TD HEIGHT=4 COLSPAN=4></TD></TR>\n";
  }
  else
  {

# *********************************************************************************************************
# These lines allow the user to modify their pop and stmp hosts
# 
# Replace the lines above with these
# *********************************************************************************************************

    print "<TR>\n";
    print "  <TD ALIGN=RIGHT ID='pop_cell' WIDTH=200 HEIGHT=22><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>êêcreate_popserverëë</TD><TD WIDTH=5></TD><TD COLSPAN=2><FONT FACE=ncoffline SIZE=êêglobal_fontsize_medëë><INPUT TYPE=\"text\" NAME=\"pophostname\" SIZE=23></TD>\n";
    print "</TR>\n";

    print "<TR>\n";
    print "  <TD ALIGN=RIGHT ID='smtp_cell' WIDTH=200 HEIGHT=22><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>êêcreate_smtpserverëë</TD><TD WIDTH=5></TD><TD COLSPAN=2><FONT FACE=ncoffline SIZE=êêglobal_fontsize_medëë><INPUT TYPE=\"text\" NAME=\"smtphostname\" SIZE=23></TD>\n";
    print "</TR>\n";

# *********************************************************************************************************
# *********************************************************************************************************

  }

  print "<TR>\n";
  print "  <TD ALIGN=RIGHT ID='email_cell'><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>êêcreate_addressëë</TD><TD WIDTH=5></TD><TD><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë><INPUT TYPE=\"text\" NAME=\"address\" SIZE=18 VALUE=\"\"></TD>\n";
  print "  <TD ALIGN=LEFT><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë><INPUT TYPE=\"checkbox\" NAME=\"default_account\">&nbsp;êêcreate_defaultëë</TD>\n";
  print "</TR>\n";

  print "<TR>\n";
  print "  <TD ALIGN=RIGHT ID='username_cell'><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>êêcreate_usernameëë</TD><TD WIDTH=5></TD><TD COLSPAN=2><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë><INPUT TYPE=\"text\" NAME=\"username\" SIZE=18 VALUE=\"\"></TD>\n";
  print "</TR>\n";

  print "<TR>\n";
  print "  <TD ALIGN=RIGHT ID='new_password_cell'><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>êêcreate_passwordëë</TD><TD WIDTH=5></TD><TD COLSPAN=2><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë><INPUT TYPE=\"password\" NAME=\"new_password\" SIZE=18></TD>\n";
  print "</TR>\n";

  print "<TR>\n";
  print "  <TD ALIGN=RIGHT ID='retype_password_cell'><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>êêcreate_retype_passwordëë</TD><TD WIDTH=5></TD><TD COLSPAN=2><FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë><INPUT TYPE=\"password\" NAME=\"retype_password\" SIZE=18></TD>\n";
  print "</TR>\n";

  print "</FORM>\n";

  # **** Output the end of the table
  print "</TABLE>\n\n";

  print "</BODY>\n";
  print "</HTML>\n";
}


# output_buttons
#
sub output_buttons
{
  my ($n) = @_;
  my ($temp, $i);

  ($temp,$i) = split(/=/,$query,2);

  print "<TABLE WIDTH=\"100%\" ALIGN=\"CENTER\" BORDER=0 CELLSPACING=0>";
  print "  <TR>";
  print "    <TD WIDTH=\"50%\" ALIGN=CENTER>";
  print "      <FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>";
  print "      <FORM METHOD=\"GET\" ACTION=\"accounts.pl\" Target=\"_top\">";
  print "        <INPUT TYPE=HIDDEN NAME=\"path\" VALUE=\"".$public_path."\">";
  print "        <INPUT TYPE=SUBMIT VALUE=\"êêcreate_b_accountsëë\" BORDERIMAGE=\"icontype:buttmid_bord\" SELIMAGE=\"icontype:buttmid_sel\" WIDTH=110 HEIGHT=40>";
  print "      </FORM>";
  print "    </TD>";

  print "    <FONT FACE=ncoffline SIZE=êêglobal_fontsize_lgëë>";
  print "    <FORM METHOD=GET NAME=\"myform\" ACTION=\"javascript:confirm_create()\" Target=\"_top\">";

  print "    <TD WIDTH=\"50%\" ALIGN=CENTER>";
  print "        <INPUT TYPE=SUBMIT VALUE=\"êêcreate_b_createëë\" BORDERIMAGE=\"icontype:buttmid_bord\" SELIMAGE=\"icontype:buttmid_sel\" WIDTH=110 HEIGHT=40>";
  print "    </TD>";

  print "  </TR>";
  print "</TABLE>";

}


# get_public_path
#
sub get_public_path
{
  my (@pairs, $command_type, $passed_in, $item);

  if ($query eq "")
  {
    return 0;
  }

  @pairs    = split(/&/,$query);

  foreach $item(@pairs)
  {
    ($command_type,$passed_in) = split(/=/,$item,2);

    if ($command_type eq "path")
    {
      $public_path = $passed_in;
      $public_path =~ s/%2F/\//g;

      return 1;
    }
  }

  return 0;
}
