.TH mnAccept 3 "31 August 1994"
.SH NAME
mnAccept - accept a connection request
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnt.h>
.LP
mnp *mnAccept(mnp *port);
.SH DESCRIPTION
port is a port created with the stream protocol.  mnAccept() extracts
the first pending connection request and creates a new port with the
same properties as the original port except that it is connected to the
port which initiated the connection request.  The new port is used to
read and write data from and to the port which initiated the connection,
but cannot be used to accept further connections.  The original port
remains open and available to accept further connections.
.LP
If no connection requests are pending, mnAccept() will normally block
until one arrives unless the port is in a non-blocking mode.  mnListen(3)
may be used to listen for a request for accepting.
.SH RETURN VALUES
On success, mnAccept() returns the newly connected port.  Otherwise,
it returns null, and mnLastError() will indicate one of the following
errors:
.TP 20
MNSTS_ABORTED
The blocking operation was aborted.
.TP 20
MNERR_WOULDBLOCK
No connection request was available and the port is in a non-blocking
mode.
.SH SEE ALSO
mnListen(3), mnConnect(3), mnOpen(3), mnstr(4P).
