.TH mnClose 3 "31 August 1994"
.SH NAME
mnClose - close a port
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnt.h>
.LP
void mnClose(mnp *port);
.SH DESCRIPTION
mnClose() closes a port returned by mnOpen() or mnAccept().
.LP
Data sent prior to the close will still be sent in a reliable manner.  If
any asynchronous send operations are pending, these will still be allowed
to complete in the usual manner.
.LP
Any unread data or connection requests are discarded.  For a connected
port, the connection is dissolved.  Either side
of the stream may choose to close the connection at any time.  Reads
on the stream will retrieve all data up to the point of the disconnect
by the sender.  Sends on the stream will report an error if the receiver
has disconnected.
.LP
Closing a port returned by mnAccept() does not affect the original
passive stream port.
.SH SEE ALSO
mnAccept(3), mnConnect(3), mnOpen(3), mnmsg(4P), mnstr(4P).
