.TH mnConnect 3 "31 August 1994"
.SH NAME
mnConnect - initiate a connection
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnt.h>
.LP
sb4 mnConnect(mnp *port, mna *to);
.SH DESCRIPTION
port is a port created with the stream protocol.  to is a Media Net
address that identifies another stream-based port.  mnConnect() initiates
a connection from one port to the other.  A port may be connected only
once.  Once connected, the port may be used to read and write data from
and to the other port.
.SH USAGE
This routine actually causes no network communication to take place.
It merely prepares the port.  Not until the first mnWrite(3) is done
will the destination port actually receive the connection request.
For most application, this is not a problem.  For those applications
which require one side to connect only to receive data from the other
side, an artificial one-byte leader may be sent to initiate the connection.
The accepting side can anticipate this one byte and discard it.
.SH RETURN VALUES
On success, mnConnect() returns 0.  Otherwise, it may return one of
the following errors:
.TP 20
MNERR_ALREADY
The given port is already connected.
.TP 20
MNERR_BADPARAM
The given port is not a stream port.
.SH SEE ALSO
mnAccept(3), mnOpen(3), mnstr(4P).
