.TH mnDiscard 3 "31 August 1994"
.SH NAME
mnDiscard - asynchronous handler for discarded results
.SH SYNOPSIS
.nf
#include <mn.h>
.LP
void mnDiscard(void *, sb4);
.SH DESCRIPTION
mnDiscard() is an asynchronous handler that does nothing.  It may be
used to start operations asynchronously where the outcome of the operation
may safely be ignored.
.SH SEE ALSO
mn_intro(3).
