.TH mnError 3 "31 August 1994"
.SH NAME
mnError, mnLastError - Media Net error messages
.SH SYNOPSIS
.nf
#include <mn.h>
.LP
const char *mnError(sb4 err);
.LP
sb4 mnLastError(void);
.SH DESCRIPTION
mnError() returns a short text description of the error passed in as an
argument.  This may be any value returned by a routine or operation.
.LP
mnLastError() returns the last error detected by a routine that cannot
report errors directly because its return type is not an sb4.  The value
returned is only meaningful after the failure of such a routine.
Asynchronous operations never affect the value returned by this routine.
.SH SEE ALSO
mn_intro(3).
