.TH mnGetAddr 3 "31 August 1994"
.SH NAME
mnGetAddr, mnGetPeer - get port address and peer address
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnt.h>
.LP
void mnGetAddr(mnp *port, mna *addr);
.LP
sb4 mnGetPeer(mnp *port, mna *peer);
.SH DESCRIPTION
mnGetAddr() writes the Media Net address assigned to port into addr.
.LP
mnGetPeer() writes the Media Net address of the peer to which the
port is connected into addr.  If the port is unconnected, mnGetPeer()
returns MNERR_NOTCONN.
.SH SEE ALSO
mnAccept(3), mnConnect(3), mnOpen(3).
