.TH mnGetCwd 3 "13 December 1994"
.SH NAME
mnGetCwd - get current working directory
.SH SYNOPSIS
.nf
#include <mn.h>
.LP
char *mnGetCwd(void);
.SH DESCRIPTION
mnGetCwd() returns the current working directory.   This value is usually
obtained from the environment variable OMN_CWD during Media Net initialization.
If not set, the current working directory defaults to "/".
.SH SEE ALSO
mznm(8).
