.TH mnGetOptions 3 "31 August 1994"
.SH NAME
mnGetOptions, mnSetOptions - get and set port options
.SH SYNOPSIS
.nf
#incude <mn.h>
#include <mnt.h>
.LP
void mnSetOptions(mnp *port, ub4 options);
.LP
ub4 mnGetOptions(mnp *port);
.SH DESCRIPTION
mnGetOptions() and mnSetOptions() manipulate options associated with
a port.
.LP
The following option may used:
.TP 20
MNOPT_NONBLOCK
Non-blocking mode.  When in non-blocking mode, writes will fail rather
than block if there is insufficient buffer space; reads will fail rather
than block if there is no unread data available.
.SH RETURN VALUES
mnGetOptions() returns the options currently set on the port.
.SH SEE ALSO
mnOpen(3), mnRead(3), mnRecv(3), mnSend(3), mnWrite(3).
