.TH mnOpen 3 "31 August 1994"
.SH NAME
mnOpen - open a port
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnt.h>
.LP
mnp *mnOpen(mnProto protocol);
.SH DESCRIPTION
A port is an endpoint used for communication.  mnOpen creates a port
and returns a pointer to it.  A port may be used to both send and
receive data.
.LP
The port uses the transport protocol specified by protocol.  Possible
protocols are:
.LP
.RS
.nf
MNPROTO_MESSAGE
MNPROTO_STREAM
.fi
.RE
.LP
The MNPROTO_MESSAGE protocol provides for the reliable transport of
discrete messages of a finite length.  The MNPROTO_STREAM protocol
provides for the reliable transport of an infinite byte stream. 
.SH RETURN VALUES
On success, mnOpen() returns a pointer to a port.  Otherwise, it
returns null and mnLastError() will indicate one of the following
errors:
.TP 20
MNERR_BADPARAM
The protocol specified is invalid.
.SH SEE ALSO
mnAccept(3), mnClose(3), mnConnect(3), mnRead(3), mnRecv(3),
mnSend(3), mnWrite(3), mnmsg(4P), mnstr(4P).
.SH BUGS
There is no unreliable transport protocol publicly available.
