.TH mnrAllow 3 "31 August 1994"
.SH NAME
mnrAllow, mnrDisallow - control arrival of new clients
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnrs.h>
.LP
void mnrAllow(mnrs *sh);
.LP
void mnrDisallow(mnrs *sh);
.SH DESCRIPTION
sh is a server handle created by mnrCreateServer(3).  These routines
alter the behavior of mnrListen(3).  Normally, when mnrListen() is
called, it will accept requests from clients that may not have an
already established context with the server.  If mnrDisallow() is
called, then only calls from clients who already have obtained
contexts from this particular server thread will be accepted by
mnrListen().  mnrAllow() will reenable the acceptance of new clients.
.LP
By default, calls from new clients are accepted.
.SH USAGE
mnrAllow() and mnrDisallow() are generally used by context-based servers
after the server thread has accepted as many clients as it can support
concurrently.  It then disallows further clients from calling the
server until one of the existing clients finishes.  Then, it may allow
a new client to create a context.
.LP
These routines only work if the process server is being used.
.SH SEE ALSO
mnrCreateServer(3), mnrCtxCreate(3), mnrListen(3).
