.TH mnrConfig 3 "31 August 1994"
.SH NAME
mnrConfig - configure memory allocator for RPC
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnr.h>
.LP
void mnrConfig(mnAlloc alloc, mnFree free);
.SH DESCRIPTION
mnrConfig() sets the memory allocation and deallocation routines used
by Media Net RPC.
.LP
This routine may be called repeatedly to alter the routines used
to manage RPC-related memory.  The memory management routines passed
to mnInit() are used if this routine is not called.
.SH SEE ALSO
mnInit(3).
