.TH mnrDestroyServer 3 "31 August 1994"
.SH NAME
mnrDestroyServer - destroy an RPC server handle
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnrs.h>
.LP
void mnrDestroyServer(mnrs *sh);
.SH DESCRIPTION
sh is a server handle previously created by mnrCreateServer().
mnrDestroyServer() destroys sh and all associated resources.  Any
open client contexts are destroyed.  If the server is registered,
it will be automatically unregistered by this call.
.LP
mnrDestroyServer() is automatically invoked on any existing
server handle by mnTerm().
.SH WARNINGS
mnrDestroyServer() must not be called from within a server dispatch
routine.
.SH SEE ALSO
mnTerm(3), mnrCreateServer(3).
