.TH mnrFreeHandle 3 "31 August 1994"
.SH NAME
mnrFreeHandle - free a binding handle
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnrc.h>
.LP
void mnrFreeHandle(mnrb *bh);
.SH DESCRIPTION
bh is a binding handle created by mnrFindServer() or mnrMakeHandle().
mnrFreeHandle() is used to destroy a binding handle and release all
resources associated with the binding handle.  In particular, any open
context handles are destroyed, and any pending RPC calls are cancelled.
.LP
mnrFreeHandle() is called automatically on each open binding handle
upon mnTerm(3).
.SH SEE ALSO
mnTerm(3), mnrFindServer(3), mnrMakeHandle(3).
