.TH mnrGetAddr 3 "31 August 1994"
.SH NAME
mnrGetAddr, mnrGetUsrp - get server information
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnrs.h>
.LP
void mnrGetAddr(mnrs *sh, mna *addr);
.LP
void *mnrGetUsrp(mnrs *sh);
.SH DESCRIPTION
mnrGetAddr() writes the Media Net address associated with the server
handle into addr.
.LP
mnrGetUsrp() returns the value passed as the usrp argument to
mnrCreateServer() when the given server handle was created.
This pointer may be used to refer to any thread-wide context
needed by the server.
.SH SEE ALSO
mnrCreateServer(3).
