.TH mnrGetPeer 3 "31 August 1994"
.SH NAME
mnrGetPeer, mnrGetHandle - get call information
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnrs.h>
.LP
void mnrGetPeer(mnrsc *call, mna *addr);
.LP
mnrs *mnrGetHandle(mnrsc *call);
.SH DESCRIPTION
mnrGetPeer() writes the Media Net address of the client who made the
call into addr.
.LP
mnrGetHandle() returns the server handle associated with the call
descriptor.
.SH SEE ALSO
mnrCreateServer(3), mnrGetNextCall(3).
