.TH mnrGetServerAddr 3 "8 December 1994"
.SH NAME
mnrGetServerAddr - get server address from binding handle
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnrc.h>
.LP
void mnrGetServerAddr(mnrb *bh, mna *addr);
.SH DESCRIPTION
mnrGetServerAddr() gets the Media Net address of the server to which
the client is bound by the given binding handle.  The address is
written to addr.  For multi-instanced servers, this address may
be that of a service queue and not that of an individual server instance.
.SH SEE ALSO
mnrMakeHandle(3), mnrFindServer(3), mnsc(8).
