.TH mnrIdCmp 3 "31 August 1994"
.SH NAME
mnrIdCmp - compare two RPC identifiers
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnr.h>
.LP
sb4 mnrIdCmp(const mnrid *first, const mnrid *second,
	boolean exact);
.SH DESCRIPTION
mnrIdCmp() compares its arguments and returns a value less than zero,
equal to zero, or greater than zero as first is less than, equal to,
or greater than second.  Ordering is relevant only as far as version
numbers are concerned.  If the id fields are not equal, then an
arbitrary non-zero value is returned.
.LP
Assuming the id fields are equal, the major version numbers are first
compared independently of the release number.  If not equal, then the
higher version number is considered greater.  If the major version
numbers are equal, then the release numbers are compared.  The higher
release number is considered greater; however, if exact is FALSE,
then if the first release number is greater than or equal to the
second, then the two are considered equal.  This supports the notion
of "compatible" versions.
.SH SEE ALSO
mnrpc_intro(3).
