.TH mnrMakeHandle 3 "31 August 1994"
.SH NAME
mnrMakeHandle - make a binding handle
.SH SYNOPSIS
.nf
#include <mn.h>
#include <mnrc.h>
.LP
mnrb *mnrMakeHandle(const mna *);
.SH DESCRIPTION
mnrMakeHandle() is used to make a binding handle that refers to a
particular server known by an address.  Once the binding handle is
created, it may be used repeatedly.  It may be freed with
mnrFreeHandle(3).
.LP
No check is made to see if the address identifies a valid server
until the first call is made using the handle.
.SH RETURN VALUES
This routine returns the newly-created binding handle.
.SH SEE ALSO
mnrFindServer(3), mnrFreeHandle(3).
