.TH mnSet 3 "31 August 1994"
.SH NAME
mnSet - set a semaphore
.SH SYNOPSIS
.nf
#include <mn.h>
.LP
void mnSet(mnsem *sem, sb4 val);
.SH DESCRIPTION
mnSet() sets a semaphore to the given value.
.SH USAGE
mnSet() is useful for programs which would like to use Media Net-style
semaphores for their own operations.  Following mnSemAlloc(), all of
the usual semaphore-related routines may be used to test or wait on
the semaphore.  mnSet() actually allows the value of the semaphore to
be set.
.LP
Note that setting a value of -1 will not be recognized as setting the
semaphore.  Setting a semaphore that has been passed to Media Net
will effectively cause Media Net to ignore the result of the operation
just as mnSemFree() would.  The difference is that the program could
continue to test its value.
.SH SEE ALSO
mnTimer(3), mnsem(3), mn_intro(3).
