.TH mnTerm 3 "31 August 1994"
.SH NAME
mnTerm - terminate Media Net
.SH SYNOPSIS
.nf
#include <mn.h>
.LP
void mnTerm(void);
.SH DESCRIPTION
mnTerm() terminates Media Net.  Terminating Media Net involves the
following sequence of actions:
.TP 3
+
Destroy all bind handles; this will cause any client contexts to be
freed.
.TP 3
+
Destroy all server handles; this will cause any server running within
the process to be unregistered.
.TP 3
+
All open ports are closed.
.TP 3
+
All pending asynchronous operations are terminated.
.LP
mnTerm() must only be called once per process.  Following termination,
the original heap (if any) may be freed and the logging output closed.
.SH SEE ALSO
mnrFreeHandle(3), mnrDestroyServer(3), mnClose(3), mnInit(3).
