.TH mnTimer 3 "31 August 1994"
.SH NAME
mnTimer - establish a timer
.SH SYNOPSIS
.nf
#include <mn.h>
.LP
sb4 mnTimer(ub4 timeout, mnHandler handler, dvoid *usrp);
.SH DESCRIPTION
mnTimer() sets up a timer that will be triggered after timeout milliseconds.
The handler and usrp arguments are interpreted in the usual way.
.SH USAGE
mnTimer() is useful for programs which use timer events and would like
to handle them in canonical way.  The accuracy of the timer is only as
good as however often mnIdle(3) is called if the timer is queued
asynchronously.
.SH RESULT VALUES
The completion of the operation always returns MNERR_TIMEOUT.
.SH RETURN VALUES
In synchronous mode, the routine itself will return either MNERR_TIMEOUT
or MNSTS_ABORTED if aborted by a busy-wait routine.
.LP
In asynchronous mode, the routine itself will return 0 if the timer was
created.
.SH SEE ALSO
mnIdle(3).
