.TH mnVersion 3 "31 August 1994"
.SH NAME
mnVersion - get version of Media Net
.SH SYNOPSIS
.nf
#include <mn.h>
.LP
char *mnVersion(char *buf, size_t len);
.SH DESCRIPTION
mnVersion() writes a string describing the current version of Media Net
to buf.  A maximum of len characters will be written.  A sufficient
maximum buffer length is 128 bytes.  As a convenience, it returns the
pointer to buf that was passed in.
